apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html/data.geojson
        - name: index
          mountPath: /usr/share/nginx/html/index.html
  volumes:
    - name: index
      hostPath:
        path: ./index.html
        type: File
    - name: data
      hostPath:
        path: ./data.geojson
        type: File
