apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: html
      hostPath:
        path: ./static/
        type: Directory
